# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: legal_case.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10legal_case.proto\x12\x12legal.organization"\xd4\x01\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\x05\x12\x0c\n\x04path\x18\x05 \x01(\t\x12<\n\x08metadata\x18\x06 \x03(\x0b\x32*.legal.organization.Document.MetadataEntry\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"M\n\rWorkflowStage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05order\x18\x04 \x01(\x05"\xf1\x01\n\x04\x43\x61se\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x15\n\rpractice_area\x18\x03 \x01(\t\x12\x14\n\x0cjurisdiction\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12+\n\tsub_cases\x18\x06 \x03(\x0b\x32\x18.legal.organization.Case\x12/\n\tdocuments\x18\x07 \x03(\x0b\x32\x1c.legal.organization.Document\x12\x33\n\x08workflow\x18\x08 \x03(\x0b\x32!.legal.organization.WorkflowStage"<\n\x11LegalOrganization\x12\'\n\x05\x63\x61ses\x18\x01 \x03(\x0b\x32\x18.legal.organization.CaseBI\n\x1e\x63om.hiclass.legal.organizationH\x01Z%github.com/hiclass/legal/organizationb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "legal_case_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\036com.hiclass.legal.organizationH\001Z%github.com/hiclass/legal/organization"
    _DOCUMENT_METADATAENTRY._options = None
    _DOCUMENT_METADATAENTRY._serialized_options = b"8\001"
    _DOCUMENT._serialized_start = 41
    _DOCUMENT._serialized_end = 253
    _DOCUMENT_METADATAENTRY._serialized_start = 206
    _DOCUMENT_METADATAENTRY._serialized_end = 253
    _WORKFLOWSTAGE._serialized_start = 255
    _WORKFLOWSTAGE._serialized_end = 332
    _CASE._serialized_start = 335
    _CASE._serialized_end = 576
    _LEGALORGANIZATION._serialized_start = 578
    _LEGALORGANIZATION._serialized_end = 638
# @@protoc_insertion_point(module_scope)
